[theme]
base = "light"
primaryColor = "#0C7C59"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#111827"
font = "sans serif"

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true
